name: dompetku
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0' # Menggunakan rentang versi yang lebih aman

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.2.0
  google_fonts: ^6.2.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.0.0
  fl_chart: ^0.71.0
  table_calendar: ^3.1.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
