name: dompetku
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0' # Menggunakan rentang versi yang lebih aman

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.2.0
  google_fonts: ^6.2.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  
  # ðŸ“Š Tambahan untuk grafik & kalender
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
